"""
Builds slides.pptx for the course presentation. Reads real numbers from
docs/training_metrics.json and docs/model_comparison.json when available
(falls back to placeholders so this is safe to run at any point), and embeds
the real charts from app/static/charts/ (regenerated by train_classifier.py
and insights.py, never hand-drawn).

Visual design: a small set of layout helpers (header band, stat cards, bullet
lists, image grids) applied consistently across every slide, using one color
palette that matches app/static/style.css - the slides and the live demo look
like the same project, not two unrelated deliverables.

Usage (from the repo root):
    python docs/slides/generate_slides.py
"""

import json
import os

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_CONNECTOR, MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.oxml.xmlchemy import OxmlElement
from pptx.util import Emu, Inches, Pt

DOCS_DIR = os.path.join(os.path.dirname(__file__), "..")
METRICS_PATH = os.path.join(DOCS_DIR, "training_metrics.json")
COMPARISON_PATH = os.path.join(DOCS_DIR, "model_comparison.json")
# Eval-partition headline numbers, written by pipeline/insights.py. The two files
# above are dev-only, so without this the deck had no eval-set accuracy on it at
# all - only the per-attack bar chart, which shows bars but states no number.
STREAMING_PATH = os.path.join(DOCS_DIR, "streaming_metrics.json")
CHARTS_DIR = os.path.join(DOCS_DIR, "..", "app", "static", "charts")
OUT_PATH = os.path.join(os.path.dirname(__file__), "slides.pptx")

# --- palette: matches app/static/style.css so the deck and the live demo read as one project ---
NAVY = RGBColor(0x0F, 0x29, 0x42)
TEAL = RGBColor(0x0D, 0x94, 0x88)
RED = RGBColor(0xDC, 0x26, 0x26)
BLUE = RGBColor(0x2B, 0x6C, 0xB0)
DARK_TEXT = RGBColor(0x1A, 0x20, 0x2C)
MUTED = RGBColor(0x64, 0x74, 0x8B)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BG = RGBColor(0xF7, 0xF9, 0xFB)
CARD_BG = RGBColor(0xFF, 0xFF, 0xFF)
BORDER = RGBColor(0xE2, 0xE8, 0xF0)
LIGHT_TEXT = RGBColor(0xCB, 0xD5, 0xE1)

FONT = "Calibri"
SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)
HEADER_H = Inches(1.15)
MARGIN = Inches(0.6)


def load_json(path):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return None


def _no_shadow(shape):
    shape.shadow.inherit = False


def _rect(slide, left, top, width, height, color, line=False):
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    if not line:
        shape.line.fill.background()
    _no_shadow(shape)
    return shape


def _rounded_rect(slide, left, top, width, height, color, border_color=None):
    shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height)
    shape.adjustments[0] = 0.06
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    if border_color:
        shape.line.color.rgb = border_color
        shape.line.width = Pt(1)
    else:
        shape.line.fill.background()
    _no_shadow(shape)
    return shape


def _textbox(slide, left, top, width, height, text, size=16, bold=False, color=DARK_TEXT, align=PP_ALIGN.LEFT, anchor=None):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    if anchor:
        tf.vertical_anchor = anchor
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = bold
    p.font.color.rgb = color
    p.font.name = FONT
    p.alignment = align
    return box


def new_slide(prs):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # fully blank layout - full manual control
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = BG
    return slide


def add_header(prs, title, subtitle=None, slide_num=None):
    slide = new_slide(prs)
    _rect(slide, 0, 0, SLIDE_W, HEADER_H, NAVY)
    _rect(slide, 0, HEADER_H, Inches(2.3), Pt(5), TEAL)

    title_box = slide.shapes.add_textbox(MARGIN, Inches(0.16), SLIDE_W - Inches(1.2), Inches(0.7))
    tf = title_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(30)
    p.font.bold = True
    p.font.color.rgb = WHITE
    p.font.name = FONT

    if subtitle:
        sub_box = slide.shapes.add_textbox(MARGIN, Inches(0.72), SLIDE_W - Inches(1.2), Inches(0.4))
        sp = sub_box.text_frame.paragraphs[0]
        sp.text = subtitle
        sp.font.size = Pt(13)
        sp.font.color.rgb = LIGHT_TEXT
        sp.font.name = FONT

    if slide_num is not None:
        _textbox(
            slide, SLIDE_W - Inches(0.9), SLIDE_H - Inches(0.42), Inches(0.6), Inches(0.32),
            str(slide_num), size=11, color=MUTED, align=PP_ALIGN.RIGHT,
        )
    return slide


def add_bullets(slide, bullets, top=Inches(1.55), width=None, size=19, height=None):
    """Every bullet is one complete sentence/point, same size and color -
    PowerPoint's own word-wrap (word_wrap=True below) handles long lines by
    wrapping onto a second visual line automatically, so there's no need to
    (and no reason to) manually pre-split long bullets into fragments."""
    width = width or (SLIDE_W - 2 * MARGIN)
    # height is passed on the pipeline-stage slides, where the architecture strip
    # occupies the foot of the slide and the text must stop short of it.
    box = slide.shapes.add_textbox(MARGIN, top, width, height or (SLIDE_H - top - Inches(0.5)))
    tf = box.text_frame
    tf.word_wrap = True
    for i, bullet in enumerate(bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = "•  " + bullet.strip()
        p.font.size = Pt(size)
        p.font.color.rgb = DARK_TEXT
        p.font.name = FONT
        p.space_after = Pt(12)
    return box


def add_button(slide, text, url, left, top, width=Inches(3.6), height=Inches(0.65), color=TEAL):
    """A clickable rounded-rectangle CTA. PowerPoint (and the .pptx format)
    supports real hyperlinks on shapes via click_action - this isn't a static
    image of a button, clicking it in Slide Show mode actually opens the URL
    in the system's default browser."""
    shape = _rounded_rect(slide, left, top, width, height, color)
    shape.click_action.hyperlink.address = url
    tf = shape.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(17)
    p.font.bold = True
    p.font.color.rgb = WHITE
    p.font.name = FONT
    p.alignment = PP_ALIGN.CENTER
    tf.vertical_anchor = MSO_ANCHOR.MIDDLE
    return shape


def _diagram_node(slide, left, top, width, height, title, subtitle=None, fill=CARD_BG, border=TEAL,
                  text_color=DARK_TEXT, title_size=Pt(12.5)):
    """A flowchart box for the architecture diagram - a rounded rect with a bold
    title and an optional smaller gray subtitle line underneath.

    text_color and title_size exist so draw_architecture() can render the same node
    filled-and-inverted when it is the highlighted stage, and at smaller type for the
    compact strip on the pipeline-stage slides."""
    box = _rounded_rect(slide, left, top, width, height, fill, border_color=border)
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = MSO_ANCHOR.MIDDLE
    tf.margin_left = Inches(0.06)
    tf.margin_right = Inches(0.06)
    tf.margin_top = 0
    tf.margin_bottom = 0
    # split on "\n" into real paragraphs - a single run's embedded "\n" doesn't
    # render as a line break in OOXML (see add_stat_cards for the same fix).
    for i, line in enumerate(title.split("\n")):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = line
        p.font.size = title_size
        p.font.bold = True
        p.font.color.rgb = text_color
        p.font.name = FONT
        p.alignment = PP_ALIGN.CENTER
    if subtitle:
        for line in subtitle.split("\n"):
            sp = tf.add_paragraph()
            sp.text = line
            sp.font.size = Pt(9.5)
            sp.font.color.rgb = MUTED
            sp.font.name = FONT
            sp.alignment = PP_ALIGN.CENTER
    return box


# --- architecture topology, defined once -------------------------------------
# Drawn at two sizes by draw_architecture(): full-slide on the architecture slide,
# and as a compact bottom strip on every pipeline-stage slide with that stage's node
# highlighted. Defining the topology once is the point - a hand-drawn strip per slide
# would drift out of sync with the real diagram the first time the pipeline changed.
# Each node: (id, full title, subtitle, short label for the compact strip).
ARCH_ROWS = [
    [
        ("kaggle", "Kaggle: ASVspoof2019 LA", "download_dataset.py", "Kaggle"),
        ("minio", "MinIO", "object store - raw audio", "MinIO"),
        ("spark", "Spark", "batch_feature_extraction.py", "Spark"),
        ("features", "Parquet +\nElasticsearch", "feature table", "Parquet + ES"),
    ],
    [
        ("train", "train_classifier.py", "RF vs Gradient Boosting ->\nmodel + EER threshold", "train_classifier"),
        ("embed", "index_embeddings.py", "standardize ->\nk-NN embeddings", "index_embeddings"),
        ("stream", "kafka_producer.py ->\nstreaming_enrichment.py", "near-real-time scoring", "kafka -> streaming"),
    ],
    [
        ("insights", "insights.py", "aggregations -> charts + RESULTS.md", "insights.py"),
        ("flask", "Flask app", "/classify + /dashboard", "Flask app"),
    ],
]
ARCH_EDGES = [
    ("kaggle", "minio"), ("minio", "spark"), ("spark", "features"),
    ("features", "train"), ("features", "embed"), ("features", "stream"),
    ("train", "insights"), ("train", "flask"),
    ("embed", "flask"),
    ("stream", "insights"), ("stream", "flask"),
]
ARCH_ROW_BORDER = [BLUE, TEAL, RED]


def draw_architecture(slide, top, height, highlight=None, compact=False):
    """Draw the pipeline topology scaled into the band starting at `top`, `height` tall.

    highlight: node id to render filled teal with inverted text, so a stage slide can
    show where it sits in the whole pipeline. compact=True drops the subtitles and uses
    the short labels and smaller type, for the strip at the foot of the stage slides.
    """
    row_gap = Inches(0.2) if compact else Inches(0.55)
    n_rows = len(ARCH_ROWS)
    row_h = Emu(int((height - row_gap * (n_rows - 1)) / n_rows))
    col_gap = Inches(0.16) if compact else Inches(0.25)
    boxes = {}
    for r, row in enumerate(ARCH_ROWS):
        row_y = top + r * (row_h + row_gap)
        node_w = Emu(int((SLIDE_W - 2 * MARGIN - col_gap * (len(row) - 1)) / len(row)))
        for c, (node_id, title, subtitle, short) in enumerate(row):
            on = node_id == highlight
            boxes[node_id] = _diagram_node(
                slide,
                MARGIN + c * (node_w + col_gap), row_y, node_w, row_h,
                short if compact else title,
                None if compact else subtitle,
                fill=TEAL if on else CARD_BG,
                border=TEAL if on else ARCH_ROW_BORDER[r],
                text_color=WHITE if on else DARK_TEXT,
                title_size=Pt(8.5) if compact else Pt(12.5),
            )
    for src, dst in ARCH_EDGES:
        a, b = boxes[src], boxes[dst]
        if a.top == b.top:  # same row: connect left-to-right
            _arrow(slide, a.left + a.width, a.top + a.height // 2, b.left, b.top + b.height // 2,
                   width=1.0 if compact else 1.25)
        else:  # across rows: connect bottom-to-top
            _arrow(slide, a.left + a.width // 2, a.top + a.height, b.left + b.width // 2, b.top,
                   width=1.0 if compact else 1.25)
    return boxes


# Vertical band the compact strip occupies on a pipeline-stage slide, and the
# matching bullet height so text never runs into it.
STRIP_TOP = Inches(5.35)
STRIP_H = Inches(1.85)
STRIP_BULLET_H = STRIP_TOP - Inches(1.55) - Inches(0.15)


def add_stage_strip(slide, highlight):
    """The compact architecture strip plus its one-line legend, for a stage slide."""
    _textbox(slide, MARGIN, STRIP_TOP - Inches(0.28), SLIDE_W - 2 * MARGIN, Inches(0.25),
             "Where this stage sits in the pipeline:", size=10, color=MUTED)
    draw_architecture(slide, STRIP_TOP, STRIP_H, highlight=highlight, compact=True)


def _arrow(slide, x1, y1, x2, y2, color=MUTED, width=1.25):
    """A straight connector with a triangle arrowhead, used to draw the flow
    between architecture-diagram nodes. python-pptx has no high-level
    arrowhead property, so the <a:tailEnd> element is added directly."""
    conn = slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, x1, y1, x2, y2)
    conn.line.color.rgb = color
    conn.line.width = Pt(width)
    tail = OxmlElement("a:tailEnd")
    tail.set("type", "triangle")
    conn.line._get_or_add_ln().append(tail)
    _no_shadow(conn)
    return conn


def add_stat_cards(slide, stats, top=Inches(1.55), card_h=Inches(1.7)):
    """stats: list of (big_number, label, color). Evenly spaced across the slide width."""
    n = len(stats)
    gap = Inches(0.3)
    total_gap = gap * (n - 1)
    card_w = Emu(int((SLIDE_W - 2 * MARGIN - total_gap) / n))
    for i, (number, label, color) in enumerate(stats):
        left = MARGIN + i * (card_w + gap)
        card = _rounded_rect(slide, left, top, card_w, card_h, CARD_BG, border_color=BORDER)
        num_box = slide.shapes.add_textbox(left, top + Inches(0.22), card_w, Inches(0.8))
        np_ = num_box.text_frame.paragraphs[0]
        np_.text = number
        np_.font.size = Pt(34)
        np_.font.bold = True
        np_.font.color.rgb = color
        np_.font.name = FONT
        np_.alignment = PP_ALIGN.CENTER
        lbl_box = slide.shapes.add_textbox(left + Inches(0.1), top + Inches(1.05), card_w - Inches(0.2), Inches(0.6))
        lbl_tf = lbl_box.text_frame
        lbl_tf.word_wrap = True
        # `.text` on a single run doesn't honor embedded "\n"s as line breaks in
        # OOXML - split into real paragraphs so multi-line labels actually wrap
        # onto separate lines instead of showing a literal backslash-n.
        for j, line in enumerate(label.split("\n")):
            lp = lbl_tf.paragraphs[0] if j == 0 else lbl_tf.add_paragraph()
            lp.text = line
            lp.font.size = Pt(12)
            lp.font.color.rgb = MUTED
            lp.font.name = FONT
            lp.alignment = PP_ALIGN.CENTER


def add_table(slide, headers, rows, top=Inches(1.7), col_widths=None, highlight_rows=None,
              row_h=Inches(0.55), size=15):
    """A real PowerPoint table - manually space-padding text in a proportional
    font (Calibri) doesn't actually line up into columns, so tabular data
    (like the model comparison) needs an actual table shape, not bullets.

    row_h and size are adjustable because the table height is n_rows * row_h and
    nothing here clamps it to the slide: a 6-row table at the default 0.55 is 3.3in
    tall, which runs off the bottom if it starts much below mid-slide. Callers
    placing a tall table low down must budget for it (PowerPoint also treats row
    height as a minimum and will grow rows whose text wraps, so leave headroom)."""
    highlight_rows = highlight_rows or set()
    n_cols = len(headers)
    n_rows = len(rows) + 1
    width = SLIDE_W - 2 * MARGIN
    height = row_h * n_rows
    gfx = slide.shapes.add_table(n_rows, n_cols, MARGIN, top, width, height)
    table = gfx.table

    if col_widths:
        total = sum(col_widths)
        for i, w in enumerate(col_widths):
            table.columns[i].width = Emu(int(width * w / total))

    def _style_cell(cell, text, bold=False, color=DARK_TEXT, bg=None, cell_size=None):
        cell.text = str(text)
        cell.vertical_anchor = MSO_ANCHOR.MIDDLE
        cell.margin_left = Inches(0.12)
        cell.margin_right = Inches(0.12)
        p = cell.text_frame.paragraphs[0]
        p.font.size = Pt(cell_size if cell_size is not None else size)
        p.font.bold = bold
        p.font.color.rgb = color
        p.font.name = FONT
        if bg is not None:
            cell.fill.solid()
            cell.fill.fore_color.rgb = bg
        else:
            cell.fill.solid()
            cell.fill.fore_color.rgb = CARD_BG

    for j, header in enumerate(headers):
        _style_cell(table.cell(0, j), header, bold=True, color=WHITE, bg=NAVY, cell_size=size - 1)

    for i, row in enumerate(rows, start=1):
        is_highlight = (i - 1) in highlight_rows
        row_bg = RGBColor(0xE6, 0xFF, 0xFA) if is_highlight else CARD_BG
        for j, value in enumerate(row):
            _style_cell(table.cell(i, j), value, bold=is_highlight, color=TEAL if is_highlight else DARK_TEXT, bg=row_bg)

    return gfx


def add_image_row(slide, image_paths, top=Inches(1.55), caption=None):
    """Lays out 1-2 images side by side, scaled to fit, with an optional caption below."""
    existing = [p for p in image_paths if p and os.path.exists(p)]
    if not existing:
        _textbox(slide, MARGIN, top, SLIDE_W - 2 * MARGIN, Inches(0.5),
                 "(chart not generated yet - run the pipeline, then re-run this script)", size=14, color=MUTED)
        return
    available_h = SLIDE_H - top - Inches(0.6)
    n = len(existing)
    gap = Inches(0.3)
    slot_w = Emu(int((SLIDE_W - 2 * MARGIN - gap * (n - 1)) / n))
    for i, path in enumerate(existing):
        left = MARGIN + i * (slot_w + gap)
        pic = slide.shapes.add_picture(path, left, top, height=available_h)
        # if the scaled-by-height width overflows the slot, rescale by width instead
        if pic.width > slot_w:
            slide.shapes._spTree.remove(pic._element)
            pic = slide.shapes.add_picture(path, left, top, width=slot_w)
            pic.top = top + int((available_h - pic.height) / 2)
        else:
            pic.left = left + int((slot_w - pic.width) / 2)
    if caption:
        _textbox(slide, MARGIN, SLIDE_H - Inches(0.5), SLIDE_W - 2 * MARGIN, Inches(0.4),
                 caption, size=12, color=MUTED, align=PP_ALIGN.CENTER)


def main():
    metrics = load_json(METRICS_PATH)
    comparison = load_json(COMPARISON_PATH)
    streaming = load_json(STREAMING_PATH)

    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    n = [0]

    def next_num():
        n[0] += 1
        return n[0]

    # --- 1. Title slide -----------------------------------------------------
    slide = new_slide(prs)
    _rect(slide, 0, 0, SLIDE_W, SLIDE_H, NAVY)
    _rect(slide, 0, Inches(4.35), SLIDE_W, Pt(5), TEAL)
    _textbox(slide, Inches(1), Inches(2.7), Inches(11.3), Inches(1.2),
             "Human-or-AI Voice Detector", size=44, bold=True, color=WHITE)
    _textbox(slide, Inches(1), Inches(3.75), Inches(11.3), Inches(0.6),
             "BIU Big Data and AI course project — ASVspoof2019 (Logical Access)", size=18, color=LIGHT_TEXT)
    _textbox(slide, Inches(1), Inches(4.65), Inches(11.3), Inches(0.5),
             "MinIO · Apache Spark · Apache Kafka · Elasticsearch · scikit-learn · Flask",
             size=14, color=TEAL)
    _textbox(slide, Inches(1), Inches(6.35), Inches(11.3), Inches(0.5),
             "Beny Rojanski  ·  Renana Chaba  ·  Hadar Baum", size=17, color=WHITE)

    # --- 2. Problem & dataset -------------------------------------------------
    slide = add_header(prs, "Problem & dataset", slide_num=next_num())
    add_bullets(slide, [
        "Can we tell real human speech apart from AI-generated (TTS / voice-conversion) speech?",
        "ASVspoof2019 Logical Access partition: bonafide vs. spoofed utterances",
        "~121k labeled flac clips across train / dev / eval, speaker-disjoint splits",
        "PA (replay-attack) partition intentionally excluded — not AI-generated speech",
    ])

    # --- 3. Architecture diagram ---------------------------------------------
    # The bullet-list "Architecture" slide that used to precede this was removed: it
    # restated in prose what the diagram shows, and every stage now carries its own
    # highlighted copy of the diagram anyway.
    slide = add_header(prs, "Architecture", "The full pipeline, end to end - object store to serving", slide_num=next_num())

    draw_architecture(slide, Inches(1.5), Inches(4.3))

    add_button(slide, "View exact diagram in DESIGN.md",
               "https://github.com/HadarBaum/asvspoof-voice-ai/blob/main/docs/DESIGN.md",
               MARGIN, Inches(5.95), width=Inches(4.3), height=Inches(0.5), color=NAVY)
    _textbox(slide, MARGIN + Inches(4.6), Inches(6.08), SLIDE_W - MARGIN - Inches(4.6) - MARGIN, Inches(0.4),
             "Same architecture as the Mermaid flowchart in docs/DESIGN.md, redrawn natively for the deck.",
             size=11, color=MUTED)

    # --- 3c. Pipeline stage - ingest -----------------------------------------
    slide = add_header(prs, "Pipeline stage 0-1 - Ingest", "Kaggle corpus -> MinIO object store", slide_num=next_num())
    add_bullets(slide, [
        "download_dataset.py pulls the ASVspoof2019 LA corpus (~121k flac files) from Kaggle via its API "
        "into data/raw/ — a one-time step, gated on a Kaggle API token.",
        "ingest_to_minio.py uploads every labeled utterance into MinIO, an S3-compatible object store, "
        "keyed by partition and filename.",
        "32 concurrent upload threads by default — this step is I/O-bound (many small files), so "
        "threading helps a lot even though Python threads don't parallelize CPU work.",
        "Downstream steps (the Spark job, the streaming consumer, the Flask app) always fetch audio by "
        "key from MinIO, never the local filesystem — any worker, anywhere, can read a clip.",
        "Protocol metadata (speaker id, attack id, bonafide/spoof label) stays in small local text files "
        "— only the audio bytes, the actually \"big\" unstructured data, go into the object store.",
    ], size=15, height=STRIP_BULLET_H)
    add_stage_strip(slide, "minio")

    # --- 3d. Pipeline stage - transform (Spark) ------------------------------
    slide = add_header(prs, "Pipeline stage 2 - Transform", "Spark batch feature extraction — the actual \"big data\" step", slide_num=next_num())
    add_bullets(slide, [
        "batch_feature_extraction.py reads the train+dev protocol metadata and fans out across Spark "
        "executors, one task per partition of utterances.",
        "Each executor fetches its share of clips' audio bytes from MinIO and computes a fixed-length "
        "acoustic feature vector (20 MFCCs + spectral/pitch/energy statistics) via common.features."
        "extract_features — the same function used everywhere else in this project.",
        "~50k train+dev audio files decoded and feature-extracted in parallel across cores instead of "
        "one Python process working through them serially — this is the real \"big data\" step, not "
        "model training itself.",
        "Driver and executors are both pinned to sys.executable so Spark workers resolve the same "
        "Python/venv as the driver, instead of whatever `python` happens to be on PATH.",
    ], size=17, height=STRIP_BULLET_H)
    add_stage_strip(slide, "spark")

    # --- 3d(ii). Pipeline stage 2 - what's in the feature vector -------------
    slide = add_header(prs, "What's in the feature vector", "53 numbers per clip — one shared function, one fixed shape", slide_num=next_num())
    add_table(
        slide,
        ["Group", "Count", "What it captures"],
        [
            ["MFCCs (20 coeffs × mean/std)", "40", "Vocal-tract spectral envelope — timbre/voice quality, the model's top group"],
            ["Spectral shape (centroid/bandwidth/rolloff)", "6", "Brightness, spread, and energy roll-off of the spectrum"],
            ["Signal level (zero-crossing rate, RMS energy)", "4", "Noisiness and loudness over time"],
            ["Pitch (F0, 50-500Hz via librosa.yin)", "2", "Fundamental frequency mean/std, human vocal range"],
            ["Duration", "1", "Clip length in seconds"],
            ["Total", "53", "One fixed-length row per clip, any duration"],
        ],
        top=Inches(1.5),
        col_widths=[2.7, 0.7, 4.9],
        highlight_rows={5},
    )
    add_bullets(slide, [
        "Mean + std of frame-level features, not raw sequences — every clip, any length, maps to the "
        "same 53-column row a tabular classifier expects.",
        "One function, common/features.py:extract_features(), computes this for the Spark batch job, "
        "the Kafka consumer, and the live /classify endpoint — training and inference match exactly.",
        "Pitch uses plain librosa.yin, not pyin — pyin's HMM smoothing measured 2-9s/clip; across 50k+ "
        "clips, yin gets a comparable signal in ~0.02s.",
    ], top=Inches(5.72), size=12)

    # --- 3e. Pipeline stage - load --------------------------------------------
    slide = add_header(prs, "Pipeline stage 2 - Load", "Feature table -> Parquet + Elasticsearch", slide_num=next_num())
    add_bullets(slide, [
        "Every feature row the Spark job computes is written to two places at once, in the same run.",
        "Parquet (pipeline/features_train_dev.parquet) — the input train_classifier.py and "
        "index_embeddings.py train from.",
        "Elasticsearch's asvspoof-training-features index — the same rows, so aggregations/insights can "
        "run without re-reading Parquet.",
        "Elasticsearch (a NoSQL document store) goes on to hold training results, live streamed "
        "predictions, and — once standardized — dense_vector embeddings for k-NN search, all in the "
        "same cluster.",
    ], size=17, height=STRIP_BULLET_H)
    add_stage_strip(slide, "features")

    # --- 4. AI capability: classification + threshold fix -----------------
    slide = add_header(prs, "AI capability 1 — classification", "Random Forest vs. Gradient Boosting, picked by EER", slide_num=next_num())
    add_bullets(slide, [
        "Both models reweighted for the ~9:1 spoof/bonafide imbalance in training data, then compared on dev:",
    ], top=Inches(1.5), size=16)
    if comparison:
        cands = comparison["candidates"]
        selected = comparison["selected"]
        names = list(cands.keys())
        highlight = {i for i, name in enumerate(names) if name == selected}
        add_table(
            slide,
            ["Model", "EER (lower is better)", "ROC-AUC", "Deployed"],
            [
                [name.replace("_", " ").title(), f"{cands[name]['eer']:.2%}", f"{cands[name]['roc_auc']:.3f}", "✓" if name == selected else ""]
                for name in names
            ],
            top=Inches(2.15),
            col_widths=[3, 2, 2, 1.4],
            highlight_rows=highlight,
        )
        add_bullets(slide, [
            "A statistical tie on EER — the gap is ~3 clips in 2,548. Gradient Boosting is deployed "
            "for calibration and cost: 80.2% bonafide recall at the default threshold vs. 26.6%, "
            "283KB vs. 29.7MB on disk, 0.55ms vs. 27.6ms per clip.",
        ], top=Inches(4.0), size=13, height=Inches(0.95))
    else:
        add_bullets(slide, ["Run pipeline/train_classifier.py and re-generate slides for real numbers."], top=Inches(2.3))
    add_stage_strip(slide, "train")

    # --- 5. How EER is calculated --------------------------------------------
    slide = add_header(prs, "How EER is calculated", "A secondary ASVspoof2019 metric - min t-DCF was the primary one", slide_num=next_num())
    add_bullets(slide, [
        "Score every dev utterance with the model, giving each one a P(spoof) between 0 and 1.",
        "Sweep every possible decision threshold and, at each one, compute two error rates: the "
        "false-acceptance rate (bonafide clips wrongly called spoof) and the false-rejection rate "
        "(spoof clips wrongly called bonafide).",
        "As the threshold moves, one error rate goes up while the other goes down — the Equal Error "
        "Rate is the threshold where the two curves cross, i.e. where both error rates are equal.",
        "EER itself is that shared error rate at the crossing point; the threshold at that point is "
        "what actually gets deployed (see the model artifact in common/model.py).",
        "Lower EER = better separation. 0% would mean a threshold exists with zero errors of "
        "either kind; this project's deployed model scores 9.26%. EER was a secondary ASVspoof2019 "
        "metric (min t-DCF was primary) - we use it because it needs no cost model.",
    ], size=17)
    _rounded_rect(slide, Inches(0.6), Inches(5.85), SLIDE_W - Inches(1.2), Inches(1.15), CARD_BG, border_color=BORDER)
    code_box = slide.shapes.add_textbox(Inches(0.85), Inches(5.98), SLIDE_W - Inches(1.7), Inches(0.95))
    ctf = code_box.text_frame
    ctf.word_wrap = True
    for i, line in enumerate([
        "fpr, tpr, thresholds = roc_curve(y_true_spoof, y_score_spoof)",
        "fnr = 1 - tpr",
        "eer_idx = argmin(abs(fnr - fpr))   # where the two curves are closest",
        "eer, threshold = (fpr[eer_idx] + fnr[eer_idx]) / 2,  thresholds[eer_idx]",
    ]):
        p = ctf.paragraphs[0] if i == 0 else ctf.add_paragraph()
        p.text = line
        p.font.name = "Consolas"
        p.font.size = Pt(13)
        p.font.color.rgb = NAVY

    # --- 6. Results on dev: the accuracy paradox, found and fixed -----------
    # Slide order note: results are split by which partition produced them. The dev
    # results (this slide and the next) come from train_classifier.py and belong here,
    # next to the EER slide they depend on. The streamed-eval results come from
    # insights.py reading the predictions index, which only exists once the Kafka
    # consumer has run - so they sit after the streaming-enrichment slide instead of
    # before it. Nothing here should forward-reference a component not yet introduced.
    slide = add_header(prs, "Results on dev — the accuracy paradox, found and fixed", slide_num=next_num())
    if metrics:
        add_stat_cards(slide, [
            (f"{metrics['recall_bonafide_dev_default_threshold_0.5']:.0%}", "Bonafide recall\nat default 0.5 threshold", RED),
            (f"{metrics['recall_bonafide_dev']:.0%}", "Bonafide recall\nat deployed EER threshold", TEAL),
            (f"{metrics['eer_dev']:.1%}", "Equal Error Rate\n(ASVspoof's own metric)", BLUE),
        ])
        # Two single-line bullets on purpose. add_bullets does not clip - PowerPoint
        # spills text past the box - so the longer wording that used to be here wrapped
        # to four lines and ran under the table below.
        add_bullets(slide, [
            "Dev accuracy at 0.5 looked strong (94.3%), but the model was quietly biased to the majority class.",
            "Fix: the artifact stores its own EER-optimal threshold, used everywhere instead of the default 0.5.",
        ], top=Inches(3.38), size=14, height=Inches(0.8))
        # The trade-off table, not just the wins. Three of these five rows get WORSE at
        # the EER threshold - showing only the bonafide-recall gain would be picking the
        # flattering half of our own argument, and balanced accuracy is the row that
        # actually justifies the choice (and matches what the eval slides now lead with).
        gb = comparison["candidates"][comparison["selected"]]
        d05, eer_pt = gb["at_default_threshold_0.5"], gb["at_eer_threshold"]
        # Geometry, because a 6-row table does not fit here at the default row height:
        # stat cards 1.55-3.25 (card_h left at its default: add_stat_cards places the
        # label box at top+1.05 with a fixed height, so a shorter card spills its label
        # onto the slide background), bullets 3.38 + ~2 lines of 14pt = ~4.2, table
        # 4.65 + 6 * 0.46 = 7.41, and the
        # slide is 7.5 tall. Keep that sum under ~7.3 if any of these move.
        add_table(
            slide,
            ["Gradient Boosting on dev", "@ default 0.5", f"@ EER {eer_pt['threshold']:.3f}"],
            [
                ["Bonafide recall (real speech kept)", f"{d05['recall_bonafide']:.1%}", f"{eer_pt['recall_bonafide']:.1%}"],
                ["Bonafide precision (the cost)", f"{d05['precision_bonafide']:.1%}", f"{eer_pt['precision_bonafide']:.1%}"],
                ["Spoof recall (attacks caught)", f"{d05['recall_spoof']:.1%}", f"{eer_pt['recall_spoof']:.1%}"],
                ["Overall accuracy", f"{d05['accuracy']:.1%}", f"{eer_pt['accuracy']:.1%}"],
                ["Balanced accuracy (the honest headline)", f"{d05['balanced_accuracy']:.1%}", f"{eer_pt['balanced_accuracy']:.1%}"],
            ],
            top=Inches(4.65),
            col_widths=[5.6, 3.1, 3.2],
            highlight_rows={4},
            row_h=Inches(0.46),
            size=13,
        )
    else:
        add_bullets(slide, ["Run the pipeline and re-generate slides for real numbers."])

    # --- 7. Results on dev: ROC curve + feature importance ------------------
    slide = add_header(prs, "Results on dev — ROC curve & what the model learned", slide_num=next_num())
    add_image_row(slide, [
        os.path.join(CHARTS_DIR, "roc_curve.png"),
        os.path.join(CHARTS_DIR, "feature_importance.png"),
    ], caption="Both from the dev partition. Left: both candidate models, deployed model's EER point marked. "
               "Right: top acoustic features — MFCC variance dominates.")

    # --- 8. AI capability: embeddings + semantic search ---------------------
    slide = add_header(prs, "AI capability 2 — embeddings & semantic search", slide_num=next_num())
    add_bullets(slide, [
        "The same acoustic feature vectors double as embeddings — no separate embedding model needed.",
        "Standardized (zero mean, unit variance) so cosine similarity isn't dominated by whichever "
        "feature happens to have the largest raw scale.",
        "Indexed into Elasticsearch as dense_vector fields, added to the existing index in place "
        "(a mapping update, not a reindex — the 50k+ documents were already there).",
        "Powers /classify's \"most acoustically similar training clips\" — k-NN search, playable in "
        "the browser, replacing a keyword match with genuine semantic search.",
    ], height=STRIP_BULLET_H)
    add_stage_strip(slide, "embed")

    # --- 9. AI capability: streaming enrichment -----------------------------
    slide = add_header(prs, "AI capability 3 — streaming enrichment", "Kafka producer/consumer, near-real-time scoring", slide_num=next_num())
    add_bullets(slide, [
        "Producer replays eval-set utterance events (a MinIO key, not the audio itself).",
        "Consumer fetches the clip, extracts features, scores it at the deployed EER threshold, and "
        "writes an enriched prediction to Elasticsearch — one document per utterance, live.",
        "Same feature-extraction and model code as the batch job and the web app — one implementation "
        "applied three ways, not three separate things to maintain and defend.",
        "A named consumer group tracks offset, so re-running resumes instead of re-scoring.",
        "Everything on the next three slides is scored here, on the eval partition — attacks A07–A19, "
        "synthesis systems the model never saw during training.",
    ], height=STRIP_BULLET_H)
    add_stage_strip(slide, "stream")

    # --- 10. Pipeline stage - insights --------------------------------------
    slide = add_header(prs, "Pipeline stage 5 - Insights", "insights.py — Elasticsearch aggregations -> charts + RESULTS.md", slide_num=next_num())
    add_bullets(slide, [
        "Runs after the streaming consumer has written predictions — every number here is a live "
        "Elasticsearch aggregation query, nothing hand-typed or invented.",
        "Computes balanced and overall detection accuracy, per-attack-type accuracy, a confusion matrix, "
        "a confidence histogram, and class balance.",
        "Writes both a markdown report (docs/RESULTS.md) and the PNG charts /dashboard reuses — safe to "
        "re-run any time after a pipeline run (sample or full-scale) to regenerate real results.",
        "The confusion matrix, confidence histogram, and accuracy-by-attack charts on the next slides "
        "are this script's direct output, not hand-drawn. The ROC and feature-importance charts shown "
        "earlier come from train_classifier.py instead, since those need the model's own dev predictions.",
    ], size=17, height=STRIP_BULLET_H)
    add_stage_strip(slide, "insights")

    # --- 11. Results on streamed eval: confusion matrix + calibration -------
    slide = add_header(prs, "Results on streamed eval — confusion matrix & confidence", slide_num=next_num())
    add_image_row(slide, [
        os.path.join(CHARTS_DIR, "confusion_matrix.png"),
        os.path.join(CHARTS_DIR, "confidence_histogram.png"),
    ], caption="Both from the streamed eval predictions. Left: true vs. predicted counts. "
               "Right: confidence on correct vs. incorrect calls.")

    # --- 12. Results on streamed eval: headline accuracy + by attack type ---
    slide = add_header(prs, "Results on streamed eval — accuracy by attack type", "Near-perfect on most TTS/VC systems; A17/A18/A19 are the hard ones", slide_num=next_num())
    if streaming:
        # The last card is the point of the other three: on a partition this skewed,
        # a do-nothing baseline beats our own raw accuracy, so balanced accuracy is
        # the honest headline. Showing the baseline next to it makes that checkable
        # by the audience instead of something they have to take on trust.
        add_stat_cards(slide, [
            (f"{streaming['balanced_accuracy']:.1%}", "Balanced accuracy\n(mean of per-class recalls)", TEAL),
            (f"{streaming['recall_by_class']['bonafide']:.1%}", "Bonafide recall\n(real human speech)", BLUE),
            (f"{streaming['recall_by_class']['spoof']:.1%}", "Spoof recall\n(AI-generated speech)", BLUE),
            (f"{streaming['majority_baseline']:.1%}", f"Always-{streaming['majority_label']} baseline\nbeats raw accuracy ({streaming['overall_accuracy']:.1%})", RED),
        ], card_h=Inches(1.6))
        add_image_row(slide, [os.path.join(CHARTS_DIR, "accuracy_by_attack.png")], top=Inches(3.4),
                      caption=f"All figures from the {streaming['n_predictions']} streamed eval predictions "
                              f"(attacks A07–A19, unseen during training).")
    else:
        add_image_row(slide, [os.path.join(CHARTS_DIR, "accuracy_by_attack.png")],
                      caption="(run pipeline/insights.py to generate docs/streaming_metrics.json "
                              "and the headline accuracy cards)")

    # --- 12. Live demo -------------------------------------------------------
    slide = add_header(prs, "Live demo", slide_num=next_num())
    add_bullets(slide, [
        "/classify — upload a clip or record live from the microphone (captured via the Web Audio "
        "API, encoded to WAV client-side — no server changes needed for live recording).",
        "Returns Human / AI-generated + confidence, plus the 5 most similar training clips, each "
        "one playable right in the results, so you can hear what \"similar\" sounds like.",
        "/dashboard — live Elasticsearch aggregations: model comparison, threshold trade-off, ROC "
        "curve, confusion matrix, feature importance, confidence calibration.",
    ], size=18, height=Inches(2.5))
    # Buttons and caption moved up from 5.75/6.55 to clear the architecture strip.
    add_button(slide, "▶  Open /classify", "http://localhost:5000/classify", MARGIN, Inches(4.15))
    add_button(slide, "▶  Open /dashboard", "http://localhost:5000/dashboard", MARGIN + Inches(3.9), Inches(4.15), color=BLUE)
    _textbox(slide, MARGIN, Inches(4.82), SLIDE_W - 2 * MARGIN, Inches(0.3),
             "Links open localhost:5000 — click while presenting from the machine running the app (see README.md).",
             size=11, color=MUTED)
    add_stage_strip(slide, "flask")

    # --- 13. Challenges & trade-offs ------------------------------------------
    slide = add_header(prs, "Challenges & trade-offs", slide_num=next_num())
    add_bullets(slide, [
        "Windows + Spark: worker Python resolution, a path with spaces, a pyspark 3.5.1 / Python 3.12 "
        "incompatibility, and a removed distutils — four environment bugs, none in our own logic, all "
        "diagnosed and fixed rather than worked around.",
        "A bug in our own code: Random Forest was reweighted twice — class_weight and sample_weight "
        "multiply in sklearn, turning 8.8:1 into 78:1.",
        "The EER threshold trades some spoof recall for bonafide recall — a deliberate choice, not a "
        "free win: no single threshold maximizes both on an imbalanced dataset.",
        "Embedding is the classifier's own feature vector, not a separate pretrained audio embedding "
        "model — keeps the semantic-search capability fully self-contained.",
        "Kept Python end-to-end (not Scala) since the feature-extraction library is Python-only.",
        "Speaker-disjoint train/dev split (not random) to avoid inflating accuracy via leakage.",
    ], size=18)

    # --- 14. Closing ----------------------------------------------------------
    slide = new_slide(prs)
    _rect(slide, 0, 0, SLIDE_W, SLIDE_H, NAVY)
    _rect(slide, 0, Inches(3.7), SLIDE_W, Pt(5), TEAL)
    _textbox(slide, Inches(1), Inches(2.5), Inches(11.3), Inches(1.0), "Questions?", size=40, bold=True, color=WHITE)
    # The teal rule sits at y=3.70; this link used to start at y=3.55, so the rule
    # cut straight through the text. Moved below the rule with clearance.
    link_box = slide.shapes.add_textbox(Inches(1), Inches(4.15), Inches(8), Inches(0.5))
    lp = link_box.text_frame.paragraphs[0]
    lp.text = "github.com/HadarBaum/asvspoof-voice-ai"
    lp.font.size = Pt(16)
    lp.font.color.rgb = LIGHT_TEXT
    lp.font.name = FONT
    lp.runs[0].hyperlink.address = "https://github.com/HadarBaum/asvspoof-voice-ai"

    prs.save(OUT_PATH)
    print(f"Wrote {OUT_PATH} ({len(prs.slides)} slides)")


if __name__ == "__main__":
    main()
