"""
Builds slides.pptx for the course presentation. Reads real numbers from
docs/training_metrics.json and docs/model_comparison.json when available
(falls back to placeholders so this is safe to run at any point), and embeds
the real charts from app/static/charts/ (regenerated by train_classifier.py
and insights.py, never hand-drawn).

Visual design: a small set of layout helpers (header band, stat cards, bullet
lists, image grids) applied consistently across every slide, using one color
palette that matches app/static/style.css - the slides and the live demo look
like the same project, not two unrelated deliverables.

Usage (from the repo root):
    python docs/slides/generate_slides.py
"""

import json
import os

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Emu, Inches, Pt

DOCS_DIR = os.path.join(os.path.dirname(__file__), "..")
METRICS_PATH = os.path.join(DOCS_DIR, "training_metrics.json")
COMPARISON_PATH = os.path.join(DOCS_DIR, "model_comparison.json")
CHARTS_DIR = os.path.join(DOCS_DIR, "..", "app", "static", "charts")
OUT_PATH = os.path.join(os.path.dirname(__file__), "slides.pptx")

# --- palette: matches app/static/style.css so the deck and the live demo read as one project ---
NAVY = RGBColor(0x0F, 0x29, 0x42)
TEAL = RGBColor(0x0D, 0x94, 0x88)
RED = RGBColor(0xDC, 0x26, 0x26)
BLUE = RGBColor(0x2B, 0x6C, 0xB0)
DARK_TEXT = RGBColor(0x1A, 0x20, 0x2C)
MUTED = RGBColor(0x64, 0x74, 0x8B)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BG = RGBColor(0xF7, 0xF9, 0xFB)
CARD_BG = RGBColor(0xFF, 0xFF, 0xFF)
BORDER = RGBColor(0xE2, 0xE8, 0xF0)
LIGHT_TEXT = RGBColor(0xCB, 0xD5, 0xE1)

FONT = "Calibri"
SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)
HEADER_H = Inches(1.15)
MARGIN = Inches(0.6)


def load_json(path):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return None


def _no_shadow(shape):
    shape.shadow.inherit = False


def _rect(slide, left, top, width, height, color, line=False):
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    if not line:
        shape.line.fill.background()
    _no_shadow(shape)
    return shape


def _rounded_rect(slide, left, top, width, height, color, border_color=None):
    shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height)
    shape.adjustments[0] = 0.06
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    if border_color:
        shape.line.color.rgb = border_color
        shape.line.width = Pt(1)
    else:
        shape.line.fill.background()
    _no_shadow(shape)
    return shape


def _textbox(slide, left, top, width, height, text, size=16, bold=False, color=DARK_TEXT, align=PP_ALIGN.LEFT, anchor=None):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    if anchor:
        tf.vertical_anchor = anchor
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = bold
    p.font.color.rgb = color
    p.font.name = FONT
    p.alignment = align
    return box


def new_slide(prs):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # fully blank layout - full manual control
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = BG
    return slide


def add_header(prs, title, subtitle=None, slide_num=None):
    slide = new_slide(prs)
    _rect(slide, 0, 0, SLIDE_W, HEADER_H, NAVY)
    _rect(slide, 0, HEADER_H, Inches(2.3), Pt(5), TEAL)

    title_box = slide.shapes.add_textbox(MARGIN, Inches(0.16), SLIDE_W - Inches(1.2), Inches(0.7))
    tf = title_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(30)
    p.font.bold = True
    p.font.color.rgb = WHITE
    p.font.name = FONT

    if subtitle:
        sub_box = slide.shapes.add_textbox(MARGIN, Inches(0.72), SLIDE_W - Inches(1.2), Inches(0.4))
        sp = sub_box.text_frame.paragraphs[0]
        sp.text = subtitle
        sp.font.size = Pt(13)
        sp.font.color.rgb = LIGHT_TEXT
        sp.font.name = FONT

    if slide_num is not None:
        _textbox(
            slide, SLIDE_W - Inches(0.9), SLIDE_H - Inches(0.42), Inches(0.6), Inches(0.32),
            str(slide_num), size=11, color=MUTED, align=PP_ALIGN.RIGHT,
        )
    return slide


def add_bullets(slide, bullets, top=Inches(1.55), width=None, size=19, indent_sub=True):
    width = width or (SLIDE_W - 2 * MARGIN)
    box = slide.shapes.add_textbox(MARGIN, top, width, SLIDE_H - top - Inches(0.5))
    tf = box.text_frame
    tf.word_wrap = True
    for i, bullet in enumerate(bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        is_sub = indent_sub and bullet.startswith("  ")
        p.text = ("•  " + bullet.strip()) if not is_sub else ("–  " + bullet.strip())
        p.font.size = Pt(size - 3 if is_sub else size)
        p.font.color.rgb = MUTED if is_sub else DARK_TEXT
        p.font.name = FONT
        p.space_after = Pt(10)
        if is_sub:
            p.level = 1
    return box


def add_stat_cards(slide, stats, top=Inches(1.55), card_h=Inches(1.7)):
    """stats: list of (big_number, label, color). Evenly spaced across the slide width."""
    n = len(stats)
    gap = Inches(0.3)
    total_gap = gap * (n - 1)
    card_w = Emu(int((SLIDE_W - 2 * MARGIN - total_gap) / n))
    for i, (number, label, color) in enumerate(stats):
        left = MARGIN + i * (card_w + gap)
        card = _rounded_rect(slide, left, top, card_w, card_h, CARD_BG, border_color=BORDER)
        num_box = slide.shapes.add_textbox(left, top + Inches(0.22), card_w, Inches(0.8))
        np_ = num_box.text_frame.paragraphs[0]
        np_.text = number
        np_.font.size = Pt(34)
        np_.font.bold = True
        np_.font.color.rgb = color
        np_.font.name = FONT
        np_.alignment = PP_ALIGN.CENTER
        lbl_box = slide.shapes.add_textbox(left + Inches(0.1), top + Inches(1.05), card_w - Inches(0.2), Inches(0.6))
        lbl_tf = lbl_box.text_frame
        lbl_tf.word_wrap = True
        # `.text` on a single run doesn't honor embedded "\n"s as line breaks in
        # OOXML - split into real paragraphs so multi-line labels actually wrap
        # onto separate lines instead of showing a literal backslash-n.
        for j, line in enumerate(label.split("\n")):
            lp = lbl_tf.paragraphs[0] if j == 0 else lbl_tf.add_paragraph()
            lp.text = line
            lp.font.size = Pt(12)
            lp.font.color.rgb = MUTED
            lp.font.name = FONT
            lp.alignment = PP_ALIGN.CENTER


def add_table(slide, headers, rows, top=Inches(1.7), col_widths=None, highlight_rows=None):
    """A real PowerPoint table - manually space-padding text in a proportional
    font (Calibri) doesn't actually line up into columns, so tabular data
    (like the model comparison) needs an actual table shape, not bullets."""
    highlight_rows = highlight_rows or set()
    n_cols = len(headers)
    n_rows = len(rows) + 1
    width = SLIDE_W - 2 * MARGIN
    height = Inches(0.55) * n_rows
    gfx = slide.shapes.add_table(n_rows, n_cols, MARGIN, top, width, height)
    table = gfx.table

    if col_widths:
        total = sum(col_widths)
        for i, w in enumerate(col_widths):
            table.columns[i].width = Emu(int(width * w / total))

    def _style_cell(cell, text, bold=False, color=DARK_TEXT, bg=None, size=15):
        cell.text = str(text)
        cell.vertical_anchor = MSO_ANCHOR.MIDDLE
        cell.margin_left = Inches(0.12)
        cell.margin_right = Inches(0.12)
        p = cell.text_frame.paragraphs[0]
        p.font.size = Pt(size)
        p.font.bold = bold
        p.font.color.rgb = color
        p.font.name = FONT
        if bg is not None:
            cell.fill.solid()
            cell.fill.fore_color.rgb = bg
        else:
            cell.fill.solid()
            cell.fill.fore_color.rgb = CARD_BG

    for j, header in enumerate(headers):
        _style_cell(table.cell(0, j), header, bold=True, color=WHITE, bg=NAVY, size=14)

    for i, row in enumerate(rows, start=1):
        is_highlight = (i - 1) in highlight_rows
        row_bg = RGBColor(0xE6, 0xFF, 0xFA) if is_highlight else CARD_BG
        for j, value in enumerate(row):
            _style_cell(table.cell(i, j), value, bold=is_highlight, color=TEAL if is_highlight else DARK_TEXT, bg=row_bg)

    return gfx


def add_image_row(slide, image_paths, top=Inches(1.55), caption=None):
    """Lays out 1-2 images side by side, scaled to fit, with an optional caption below."""
    existing = [p for p in image_paths if p and os.path.exists(p)]
    if not existing:
        _textbox(slide, MARGIN, top, SLIDE_W - 2 * MARGIN, Inches(0.5),
                 "(chart not generated yet - run the pipeline, then re-run this script)", size=14, color=MUTED)
        return
    available_h = SLIDE_H - top - Inches(0.6)
    n = len(existing)
    gap = Inches(0.3)
    slot_w = Emu(int((SLIDE_W - 2 * MARGIN - gap * (n - 1)) / n))
    for i, path in enumerate(existing):
        left = MARGIN + i * (slot_w + gap)
        pic = slide.shapes.add_picture(path, left, top, height=available_h)
        # if the scaled-by-height width overflows the slot, rescale by width instead
        if pic.width > slot_w:
            slide.shapes._spTree.remove(pic._element)
            pic = slide.shapes.add_picture(path, left, top, width=slot_w)
            pic.top = top + int((available_h - pic.height) / 2)
        else:
            pic.left = left + int((slot_w - pic.width) / 2)
    if caption:
        _textbox(slide, MARGIN, SLIDE_H - Inches(0.5), SLIDE_W - 2 * MARGIN, Inches(0.4),
                 caption, size=12, color=MUTED, align=PP_ALIGN.CENTER)


def main():
    metrics = load_json(METRICS_PATH)
    comparison = load_json(COMPARISON_PATH)

    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    n = [0]

    def next_num():
        n[0] += 1
        return n[0]

    # --- 1. Title slide -----------------------------------------------------
    slide = new_slide(prs)
    _rect(slide, 0, 0, SLIDE_W, SLIDE_H, NAVY)
    _rect(slide, 0, Inches(4.35), SLIDE_W, Pt(5), TEAL)
    _textbox(slide, Inches(1), Inches(2.7), Inches(11.3), Inches(1.2),
             "Human-or-AI Voice Detector", size=44, bold=True, color=WHITE)
    _textbox(slide, Inches(1), Inches(3.75), Inches(11.3), Inches(0.6),
             "BIU Big Data and AI course project — ASVspoof2019 (Logical Access)", size=18, color=LIGHT_TEXT)
    _textbox(slide, Inches(1), Inches(4.65), Inches(11.3), Inches(0.5),
             "MinIO · Apache Spark · Apache Kafka · Elasticsearch · scikit-learn · Flask",
             size=14, color=TEAL)

    # --- 2. Problem & dataset -------------------------------------------------
    slide = add_header(prs, "Problem & dataset", slide_num=next_num())
    add_bullets(slide, [
        "Can we tell real human speech apart from AI-generated (TTS / voice-conversion) speech?",
        "ASVspoof2019 Logical Access partition: bonafide vs. spoofed utterances",
        "~121k labeled flac clips across train / dev / eval, speaker-disjoint splits",
        "PA (replay-attack) partition intentionally excluded — not AI-generated speech",
    ])

    # --- 3. Architecture --------------------------------------------------
    slide = add_header(prs, "Architecture", "Object store → Spark → model → streaming → Elasticsearch → Flask", slide_num=next_num())
    add_bullets(slide, [
        "MinIO (object store) holds the raw audio corpus",
        "Spark (batch, parallel across cores) extracts acoustic features from every clip",
        "Two models trained and compared — the better one (by EER) is deployed",
        "Elasticsearch (NoSQL): features + embeddings, training results, live predictions",
        "Kafka streams simulated incoming audio; a consumer scores each event in near-real-time",
        "Flask app: /classify (upload or record live, + similar-clip search) and /dashboard (insights)",
    ])

    # --- 4. AI capability: classification + threshold fix -----------------
    slide = add_header(prs, "AI capability 1 — classification", "Random Forest vs. Gradient Boosting, picked by EER", slide_num=next_num())
    add_bullets(slide, [
        "Both models reweighted for the ~9:1 spoof/bonafide imbalance in training data, then compared on dev:",
    ], top=Inches(1.5), size=16)
    if comparison:
        cands = comparison["candidates"]
        selected = comparison["selected"]
        names = list(cands.keys())
        highlight = {i for i, name in enumerate(names) if name == selected}
        add_table(
            slide,
            ["Model", "EER (lower is better)", "ROC-AUC", "Deployed"],
            [
                [name.replace("_", " ").title(), f"{cands[name]['eer']:.2%}", f"{cands[name]['roc_auc']:.3f}", "✓" if name == selected else ""]
                for name in names
            ],
            top=Inches(2.15),
            col_widths=[3, 2, 2, 1.4],
            highlight_rows=highlight,
        )
        add_bullets(slide, [
            "Selection metric is EER — the metric the ASVspoof challenge itself is scored on, not raw",
            "  accuracy, which looked strong while quietly failing bonafide clips (next slide)",
        ], top=Inches(4.0), size=16)
    else:
        add_bullets(slide, ["Run pipeline/train_classifier.py and re-generate slides for real numbers."], top=Inches(2.3))

    # --- 5. Results: the accuracy paradox, found and fixed -----------------
    slide = add_header(prs, "Results — the accuracy paradox, found and fixed", slide_num=next_num())
    if metrics:
        add_stat_cards(slide, [
            (f"{metrics['recall_bonafide_dev_default_threshold_0.5']:.0%}", "Bonafide recall\nat default 0.5 threshold", RED),
            (f"{metrics['recall_bonafide_dev']:.0%}", "Bonafide recall\nat deployed EER threshold", TEAL),
            (f"{metrics['eer_dev']:.1%}", "Equal Error Rate\n(ASVspoof's own metric)", BLUE),
        ])
        add_bullets(slide, [
            "Dev accuracy at the default threshold (94.3%) looked strong — but the model was quietly",
            "  biased toward the majority class: it caught spoof reliably, bonafide much less so",
            "Fix: the model artifact now stores its own EER-optimal decision threshold, used",
            "  everywhere (streaming consumer, web app) instead of scikit-learn's default 0.5",
            "Independently re-confirmed on live Kafka-streamed eval data, not just the dev set",
            "  it was tuned on — bonafide accuracy went 29.7% → 91.5% on the streamed sample too",
        ], top=Inches(3.55), size=16)
    else:
        add_bullets(slide, ["Run the pipeline and re-generate slides for real numbers."])

    # --- 6. Results: ROC curve + confusion matrix ---------------------------
    slide = add_header(prs, "Results — ROC curve & confusion matrix", slide_num=next_num())
    add_image_row(slide, [
        os.path.join(CHARTS_DIR, "roc_curve.png"),
        os.path.join(CHARTS_DIR, "confusion_matrix.png"),
    ], caption="Left: both candidate models, deployed model's EER point marked. Right: streamed eval predictions.")

    # --- 7. Results: feature importance + confidence calibration ------------
    slide = add_header(prs, "Results — what the model learned, and how sure it is", slide_num=next_num())
    add_image_row(slide, [
        os.path.join(CHARTS_DIR, "feature_importance.png"),
        os.path.join(CHARTS_DIR, "confidence_histogram.png"),
    ], caption="Left: top acoustic features (MFCC variance dominates). Right: confidence, correct vs. incorrect calls.")

    # --- 8. Results: accuracy by attack type --------------------------------
    slide = add_header(prs, "Results — accuracy by attack type", "Streamed eval predictions, near-perfect on most TTS/VC systems", slide_num=next_num())
    add_image_row(slide, [os.path.join(CHARTS_DIR, "accuracy_by_attack.png")])

    # --- 9. AI capability: embeddings + semantic search ---------------------
    slide = add_header(prs, "AI capability 2 — embeddings & semantic search", slide_num=next_num())
    add_bullets(slide, [
        "The same acoustic feature vectors double as embeddings — no separate embedding model",
        "Standardized (zero mean, unit variance) so cosine similarity isn't dominated by whichever",
        "  feature happens to have the largest raw scale",
        "Indexed into Elasticsearch as dense_vector fields, added to the existing index in place",
        "  (a mapping update, not a reindex — the 50k+ documents were already there)",
        "Powers /classify's \"most acoustically similar training clips\" — k-NN search, playable",
        "  in the browser, replacing a keyword match with genuine semantic search",
    ])

    # --- 10. AI capability: streaming enrichment -----------------------------
    slide = add_header(prs, "AI capability 3 — streaming enrichment", "Kafka producer/consumer, near-real-time scoring", slide_num=next_num())
    add_bullets(slide, [
        "Producer replays eval-set utterance events (a MinIO key, not the audio itself)",
        "Consumer fetches the clip, extracts features, scores it at the deployed EER threshold,",
        "  and writes an enriched prediction to Elasticsearch — one document per utterance, live",
        "Same feature-extraction and model code as the batch job and the web app — one",
        "  implementation applied three ways, not three separate things to maintain and defend",
        "A named consumer group tracks offset, so re-running resumes instead of re-scoring",
    ])

    # --- 11. Live demo -------------------------------------------------------
    slide = add_header(prs, "Live demo", slide_num=next_num())
    add_bullets(slide, [
        "/classify — upload a clip or record live from the microphone (captured via the Web",
        "  Audio API, encoded to WAV client-side — no server changes needed for live recording)",
        "Returns Human / AI-generated + confidence, plus the 5 most similar training clips —",
        "  each one playable right in the results, so you can hear what \"similar\" sounds like",
        "/dashboard — live Elasticsearch aggregations: model comparison, threshold trade-off,",
        "  ROC curve, confusion matrix, feature importance, confidence calibration",
    ])

    # --- 12. Challenges & trade-offs ------------------------------------------
    slide = add_header(prs, "Challenges & trade-offs", slide_num=next_num())
    add_bullets(slide, [
        "Windows + Spark: worker Python resolution, path-with-spaces, and a Docker Desktop",
        "  networking quirk all broke Spark's driver↔executor RPC — diagnosed and fixed, not hidden",
        "The EER threshold trades some spoof recall for bonafide recall — a deliberate choice,",
        "  not a free win: no single threshold maximizes both on an imbalanced dataset",
        "Embedding is the classifier's own feature vector, not a separate pretrained audio",
        "  embedding model — keeps the semantic-search capability fully self-contained",
        "Kept Python end-to-end (not Scala) since the feature-extraction library is Python-only",
        "Speaker-disjoint train/dev split (not random) to avoid inflating accuracy via leakage",
    ], size=17)

    # --- 13. Closing ----------------------------------------------------------
    slide = new_slide(prs)
    _rect(slide, 0, 0, SLIDE_W, SLIDE_H, NAVY)
    _rect(slide, 0, Inches(3.7), SLIDE_W, Pt(5), TEAL)
    _textbox(slide, Inches(1), Inches(2.9), Inches(11.3), Inches(1.0), "Questions?", size=40, bold=True, color=WHITE)
    _textbox(slide, Inches(1), Inches(3.9), Inches(11.3), Inches(0.5),
             "github.com/HadarBaum/asvspoof-voice-ai", size=16, color=LIGHT_TEXT)

    prs.save(OUT_PATH)
    print(f"Wrote {OUT_PATH} ({len(prs.slides)} slides)")


if __name__ == "__main__":
    main()
